import fs from 'node:fs';
import path from 'node:path';

// Una sola definición conserva los campos de las 18 tablas de Romero (2012).
// Los valores no observados nunca se convierten en resultados de auditoría.
const P = 'Simulación de auditoría SI — Autopartes Horizonte';
const pending = 'Pendiente de Odoo; no observado';
const sponsor = 'Elena Salcedo — gerente general';
const lead = 'Jose Ramos — auditor líder';
const coordinator = 'Elena Salcedo — gerente general / coordinación';
const objective = 'Evaluar controles informáticos de acceso, separación de funciones, trazabilidad, integridad y conciliación entre Inventario y Facturación de Odoo; no se trata de una auditoría real.';
const R = (cols, rows) => ({ cols, rows });
const forms = [
  { n:2, title:'Acta Constitutiva de la Auditoría', sections:[
    R(['Información preliminar','Valor'],[['Fecha','2026-09-28 (preparación documental)'],['Nombre de la Auditoría',P],['Patrocinador',sponsor],['Auditor Líder',lead],['Fecha de inicio','2026-10-05 (plan)'],['Fecha de finalización','2026-10-28 (plan)'],['Objetivos (General y Específicos)',objective+' Específicos: identificar roles; probar flujos de existencias y facturas; reconciliar movimientos; emitir recomendaciones respaldadas por capturas.']]),
    R(['Descripción general de las actividades de auditoría'],[['Definir el alcance; preparar los datos del caso; probar roles, documentos y movimientos; registrar evidencias; controlar los cambios y cerrar únicamente después de revisar los resultados.']]),
    R(['Restricciones y/o limitaciones'],[['La revisión se limita a los procesos de Inventario y Facturación, a los registros disponibles y al período definido en el plan. No incluye infraestructura física ni sistemas externos. Los resultados están sujetos a la evidencia obtenida y a la revisión de los responsables.']]),
    R(['Identificación de grupos de interés (stakeholders)'],[[sponsor],[lead],['Lucía Montes — gerente de inventario'],['Diego Ríos — gerente de facturación']]),
    R(['Fecha de entrega de informes parciales'],[['Entrega prevista para el 2026-10-19; no se ha realizado ni aprobado.']]),
    R(['Fecha','Hora','Proceso / actividad','Personal auditado'],[['2026-10-19 (prevista)','16:00 (prevista)','Inventario y facturación', 'Lucía Montes y Diego Ríos']]),
    R(['Elaborado','Aprobado'],[['Jose Ramos','Pendiente de aprobación']]) ]},
  { n:3,title:'Identificación de Involucrados',sections:[R(['Involucrado','Procesos en los que participa','Importancia'],[
    [sponsor,'Patrocinio; aceptación de entregables; control de cambios','Alta'],[lead,'Alcance, ejecución, evidencia y reporte','Alta'],['Lucía Montes — gerente de inventario (ficticia)','Productos, compras y existencias (rol supuesto)','Alta'],['Diego Ríos — gerente de facturación (ficticio)','Clientes, facturas y pagos (rol supuesto)','Alta']])]},
  { n:4,title:'Definición del Alcance de la Auditoría',sections:[R(['Campo','Valor'],[['Fecha','2026-10-09 (plan)'],['Nombre de la Auditoría',P],['Objetivo General de la Auditoría',objective]]),R(['Entregables y criterios de aceptación'],[['Alcance limitado a Inventario y Facturación de la instancia local.']]),R(['Entregable','Descripción','Criterios de aceptación'],[
    ['Entorno y datos','Instalación nativa, alternativa Compose, instrucciones y registros del caso','Odoo inicia; módulos verificados en interfaz; registros con ID y captura'],['Evidencia y trazabilidad','Capturas legibles y matriz por campo','Cada afirmación observada remite a ID y archivo existente'],['Control y cierre','Anexos 9–20 y conclusiones','No aprobar ni cerrar sin pruebas y criterios observados']]),R(['Riesgos inherentes a los entregables'],[['Riesgos residuales y medidas previstas; no implica que se haya aprobado su mitigación.']]),R(['Nombre del riesgo','Causas de Riesgo','Plan de mitigación'],[
    ['Interrupción futura de Odoo','Servicio nativo o filestore indisponible','Comprobar respaldo y recuperar en instancia aislada; reprogramar sólo nuevas pruebas'],['Privilegios excesivos','Permisos cruzados H-01 observados; cambio pendiente','Evaluar usuarios de prueba y mínimo privilegio antes de cualquier corrección autorizada'],['Descuadre existencias/facturación','Riesgo de documentos sin vínculo tras cambios posteriores','Reconciliar por ID después de cada cambio y registrar diferencias']])]},
  { n:5,title:'Programación de Actividades Proceso de Inicio',sections:[R(['Id','Nombre de la tarea','Duración','Comienzo','Fin','Predeces.'],[
    ['1','Cronograma de actividades del proyecto','18 días hábiles (plan)','2026-10-05','2026-10-28','—'],['2','Fase de Inicio del proyecto','4 días hábiles (plan)','2026-10-05','2026-10-08','—'],['3','Elaborar y enviar la propuesta','1 día','2026-10-05','2026-10-05','—'],['4','Realizar reunión con funcionarios de la empresa contratante','1 día; encuentro sólo previsto','2026-10-06','2026-10-06','3'],['5','Elaborar el Acta Constitutiva','1 día; formalización pendiente','2026-10-07','2026-10-07','4'],['6','Identificar los Involucrados','1 día','2026-10-08','2026-10-08','5'],['7','Alcance, EDT, calidad, capacitación y comunicaciones','2 días','2026-10-09','2026-10-12','6'],['8','Instalación y datos Odoo','2 días previstos; entorno realizado anticipadamente','2026-10-13','2026-10-14','7'],['9','Pruebas y capturas','3 días; pruebas técnicas anticipadas','2026-10-15','2026-10-19','8'],['10','Solicitud/ciclo de cambio','3 días; sin autorización','2026-10-20','2026-10-22','9'],['11','Seguimiento','2 días','2026-10-23','2026-10-26','10'],['12','Cierre','2 días','2026-10-27','2026-10-28','11']])]},
  { n:6,title:'Matriz de Aseguramiento de la Calidad',sections:[R(['Área','Riesgo','Causas','Consecuencias','Impacto','Probabilidad','Criterios de Aceptación'],[
    ['Software / permisos','Acceso excesivo','Permisos cruzados H-01 observados','Cambio no autorizado','Alto','Media (estimación)','Usuarios diferenciados y pruebas de acceso por registro'],['Seguridad informática','Credenciales expuestas','Secretos en archivos','Acceso indebido','Alto','Media (estimación)','Secretos fuera del repositorio y acceso local'],['Documentación','Rastro incompleto','Falta de referencias','No reproducibilidad','Alto','Media (estimación)','ID y captura por afirmación observada'],['Comunicaciones','Cambio informal','Aprobaciones verbales','Implantación no autorizada','Medio','Media (estimación)','Seis fases con fechas y responsables'],['Personal','Desconocimiento de roles','Sin capacitación','Segregación insuficiente','Medio','Media (estimación)','Registro anexo 7 y seguimiento anexo 16'],['Hardware','Equipo físico productivo','Fuera del alcance local','No evaluable','N/A','N/A','N/A: no se inspecciona infraestructura productiva'],['Instalaciones','Seguridad física empresarial','Fuera del alcance local','No evaluable','N/A','N/A','N/A: laboratorio local, sin visita a instalaciones']])]},
  { n:7,title:'Plan de Desarrollo Individual',sections:[R(['Nombre del Colaborador','Fecha'],[[lead,'2026-10-12 (plan)']]),R(['Temáticas','Tiempo para lograrlo','Entrenamiento requerido'],[['Permisos Odoo','1 mes (propuesto)','Grupos de acceso; usuario con privilegio mínimo; evidencia'],['Conciliación inventario/facturas','1 mes (propuesto)','Transferencias, valoración y asientos según edición instalada']])]},
  { n:9,title:'Informe de Estado de Auditoría',sections:[R(['Campo','Valor'],[['Para',coordinator],['De',lead],['Fecha','2026-09-29 UTC (actualización del laboratorio)'],['Alcance','Pruebas técnicas de permisos y flujo realizadas; informe no aprobado por patrocinadora'],['Cronograma','Pruebas de laboratorio adelantadas respecto del plan de octubre; sin línea base formal aprobada ni desfase calculable'],['Desarrollo de Actividades','Porcentaje global no calculable: no hay línea base aprobada ni tiempos reales consolidados. Se verificaron técnicamente compra P00013, venta S00027, recepción 19, entrega 20, facturas 27/28, pagos 1/2 y asientos 29/30. H-01 sigue pendiente de revisión.'],['Observaciones','PostgreSQL 18.6 y Odoo 18 operativos. Existencia filtro 23 = 20 + 5 - 2; batería 8 y frenos 12. Borradores 25/26 cancelados para evitar duplicidad. Ver docs/estado-odoo.json y conciliaciones.']])]},
  { n:10,title:'Solicitud de Cambios',sections:[R(['Campo','Valor'],[['Persona(s) que solicita(n) el cambio','Lucía Montes — gerente de inventario (solicitud propuesta)'],['Fecha de la solicitud','2026-10-20 (fecha prevista; aún no solicitada)'],['Solicitud Número','SC-001 (reservado; no autorizado)']]),R(['Tipo de Cambio','Marca'],[['Alcance','—'],['Presupuesto','—'],['Cronograma','—'],['Adquisiciones','—'],['Recursos','—'],['Calidad','X (propuesta)'],['Comunicaciones','—'],['Riesgos','X (propuesta)'],['Otros','—']]),R(['Razón del cambio','Marca'],[['Solicitud del cliente','—'],['Errores u omisiones','—'],['Condiciones inesperadas','X (hipótesis a verificar)'],['Oportunidad de ahorro','—'],['Orden de cambio','—']]),R(['Campo','Valor'],[['Descripción del cambio','Si las pruebas acreditan privilegios excesivos: separar permisos de inventario y facturación en cuentas de prueba; respaldar antes y probar en entorno no productivo.'],['Efecto en el costo','0 en licencias (estimación); dedicación pendiente de aprobación'],['Efecto en el cronograma','Hasta 2 días de plan propuestos; sin cambio de línea base aprobado'],['Observaciones','Solicitud hipotética: no enviada, no autorizada, no probada ni implantada.']])]},
  { n:11,title:'Plan de Contingencias',sections:[R(['Riesgo','Causas','Consecuencias','Alternativa1','Alternativa2','Alternativa3','Responsable'],[
    ['Indisponibilidad futura de Odoo','Servicio nativo caído o puerto ocupado','Interrupción de nuevas pruebas; evidencias ya capturadas permanecen','Comprobar servicio nativo y puertos','Restaurar base y filestore desde respaldo validado si procede','Reprogramar; declarar pendiente lo no probado',lead],['Pérdida de datos de laboratorio','Filestore o base dañados','No reproducibilidad','Respaldo de base y filestore','Restaurar en instancia aislada y comprobar IDs','Conservar matriz sin evidencia nueva hasta recuperar',lead],['Cambio de rol defectuoso','Permisos mal ajustados','Usuarios bloqueados','Probar cuenta no productiva','Revertir mediante copia propia verificada','Suspender implantación y notificar patrocinadora',sponsor]])]},
  { n:12,title:'Control de la Programación',sections:[R(['Id','Nombre de la tarea','Duración Real','Duración Prevista','% Completado','Variación de Duración','Comienzo','Fin','Demora Permisible'],[
    ['8','Instalación y datos Odoo','Sesiones de laboratorio 2026-09-28/29; horas no consolidadas','2 días (plan)','Hecho técnico; sin aceptación','No calculable sin tiempos reales y línea base aprobada','2026-10-13 (plan)','2026-10-14 (plan)','Se ejecutó antes del plan; no es retraso'],['9','Pruebas y capturas','Sesiones de laboratorio 2026-09-28/29; horas no consolidadas','3 días (plan)','Parcial: falta revisión humana','No calculable','2026-10-15 (plan)','2026-10-19 (plan)','Sin demora frente a fechas futuras'],['10','Control del cambio','No ejecutado: H-01 sin corrección de roles','3 días (plan)','0%','No calculable','2026-10-20 (plan)','2026-10-22 (plan)','No autorizar sin registro formal']]),R(['Regla de control','Aplicación'],[['Desfase >10%','Cuando duración real > prevista × 1,10: registrar causa y correctivo del auditor líder; sin horas verificadas no calculable.'],['Demora permisible','Si atraso respecto a fin previsto >3 días: elevar a coordinación y replantear línea base; hoy no calculable.']])]},
  { n:13,title:'Lista de Chequeo Riesgos Informáticos',sections:[R(['Área','Riesgo','Criterio de Aceptación','Sí','No','N/A','Observaciones'],[
    ['Seguridad','Acceso excesivo','Acceso mínimo por función en cuentas del caso','—','X','—','H-01: Diego (facturación) tiene escritura en compra ID 13 y venta ID 27; Lucía (inventario) en venta ID 27, con límite de UI por modelo secundario. Ver docs/hallazgos-control.md.'],['Software','Integridad','Ajustes y flujos comerciales conciliables por ID','X','—','—','Ajustes 41–43; recepción 19 y entrega 20 done; facturas vinculadas 27/28 posted y paid; pagos 1/2, asientos 29/30. Conciliaciones JSON sin diferencias.'],['Documentación','Falta de evidencia','ID y captura por resultado','X','—','—','Capturas reales y lecturas de Odoo para flujo y H-01; aprobación del informe todavía pendiente.'],['Instalaciones','Seguridad física empresarial','Inspección del local productivo','—','—','X','N/A justificado: sólo laboratorio local, empresa ficticia; no hay planta.'],['Comunicaciones','Rastro del cambio','Fechas y aprobadores por fase','—','X','—','Cambio de roles no autorizado ni implantado; no confundir con transacciones del laboratorio.']])]},
  { n:14,title:'Control de Cambios',sections:[R(['Fase','Fecha','Observaciones (evidencias)','Estatus','Responsable nombre','Cargo'],[
    ['Solicitud','2026-10-20 (prevista)','SC-001 propuesta, no emitida','Pendiente','Lucía Montes (ficticia)','gerente de inventario'],['Autorización','Posterior a solicitud real','Esperar análisis del auditor líder; no aprobar aún','Pendiente',lead,'gerente de auditoría'],['Preparación','Posterior a autorización','Respaldar y documentar permisos actuales','Pendiente',lead,'gerente de auditoría'],['Pruebas','Posterior a preparación','Probar cuenta restringida y recopilar ID/captura','Pendiente',lead,'gerente de auditoría'],['Implantación','Posterior a pruebas aprobadas','Únicamente si la prueba fue exitosa','Pendiente',lead,'gerente de auditoría'],['Cierre','Posterior a implantación verificada','Patrocinadora constata; si falla retornar a implantación','Pendiente',sponsor,'gerente general']]),R(['Auditor Líder','Firma Auditor Líder'],[[lead,'No firmada; cambio no procesado']])]},
  { n:15,title:'Matriz de Comunicaciones',sections:[R(['Involucrado','Informe de Tiempo','Informe de Actividades','Solicitud Patrocinador','Solicitud de Cambios','Reuniones Internas','Informes de Inicio','Informes de Cierre'],[
    [lead,'SC','SC','RC','RP','RM','IP','FP'],[coordinator,'—','—','—','—','RM','—','—'],[sponsor,'—','—','—','RA','RM','—','—'],['Lucía Montes y Diego Ríos — gerentes ficticios','—','—','—','RP','RA','—','—']]),R(['Simbología utilizada','Significado'],[['Frecuencia','S semanal; I inicio; F final; R cuando sea requerido'],['Destinatario','A auditor líder; C coordinador; P patrocinadora; M miembros del equipo'],['Medio / control','Correo electrónico propuesto; no se afirma envío. Registrar fecha, destinatario, acuse e identificador antes de marcar comunicado.']])]},
  { n:16,title:'Seguimiento al Plan de Desarrollo Individual',sections:[R(['Nombre del Colaborador','Fecha'],[[lead,'2026-09-28 (registro previo; revisión programada 2026-10-30)']]),R(['Temáticas','Tiempo para lograrlo','Entrenamiento requerido','Estatus del entrenamiento','Fecha de revisión','Comentarios'],[['Permisos Odoo','1 mes','Grupos y prueba de usuario','Pendiente (no A tiempo/Atrasado todavía)','2026-10-30 (prevista)','Al llegar la fecha marcar A tiempo o Atrasado y definir correctivo si corresponde.'],['Conciliación','1 mes','Inventario y factura','Pendiente (no A tiempo/Atrasado todavía)','2026-10-30 (prevista)','Hubo pruebas técnicas; no equivalen a capacitación impartida.']])]},
  { n:17,title:'Informe de Auditoría',sections:[R(['Patrocinador','Auditor Líder'],[[sponsor,lead]]),R(['Objetivo General de la Auditoría'],[[objective]]),R(['Procesos Auditados','Fecha','Lugar'],[['Inventario y Facturación del laboratorio','2026-09-28/29 (sesiones técnicas)','audit_sim local; sin auditoría empresarial real']]),R(['Área','Criterio de Aceptación','Sí','No','N/A','Hallazgo','Recomendaciones'],[
    ['Acceso','Acceso mínimo por proceso','—','X','—','H-01: permiso de escritura cruzado en compra ID 13 y venta ID 27, observado sin modificar documentos.','Revisar grupos y reglas sólo tras autorización de cambio; ver docs/hallazgos-control.md'],['Inventario / Facturación','Trazabilidad y conciliación con ID','X','—','—','Entrada 5 y salida 2 confirman filtro 23; facturas 27/28 y pagos 1/2 enlazados a órdenes y asientos; ver JSON de conciliación.','Conservar capturas e IDs y repetir prueba tras cualquier cambio de roles'],['Documentación','Evidencia técnica por resultado','X','—','—','Capturas Odoo y JSON disponibles; evaluación final pendiente de revisión humana.','No cerrar ni atribuir firma sin aceptación expresa']]),R(['Elaborado','Aprobado'],[[lead,'Informe técnico preparado; aprobación y opinión final pendientes']])]},
  { n:18,title:'Relación de Activos de Procesos',sections:[R(['Código del Activo','Nombre','Descripción','Fecha de Almacenamiento','Lugar de almacenamiento','Observaciones'],[
    ['A-01','EDT','Jerarquía basada en tabla I','2026-09-28','docs/EDT.md','Documento de diseño'],['A-02','Cronograma','Línea base propuesta','2026-09-28','docs/cronograma.csv','Fechas futuras no equivalen a duración real'],['A-03','Formularios','18 plantillas y 18 versiones diligenciadas editables','2026-09-29','formularios/','Capturas documentales separadas de evidencia Odoo'],['A-04','Capturas Odoo','Usuarios, movimientos, órdenes, facturas y pagos observados','2026-09-29','evidencias/odoo/','Referencias individuales en docs/trazabilidad.csv'],['A-05','Conciliaciones','Existencias y vínculos orden-transferencia-factura-pago-asiento','2026-09-29','docs/conciliacion-inventario.json y docs/conciliacion-financiera.json','Lecturas de laboratorio, sin dinero real'],['A-06','Respaldo previo','pg_dump y filestore antes de confirmar flujos','2026-09-29','odoo/backups/','Local e ignorado; restauración no ejecutada']]),R(['Elaborado','Aprobado'],[[lead,'Pendiente: '+coordinator]])]},
  { n:19,title:'Relación de Lecciones Aprendidas',sections:[R(['Código de Lección Aprendida','Entregable afectado','Descripción y Causa del problema','Acción Correctiva','Resultado obtenido','Lección Aprendida'],[
    ['LA-01','Entorno Odoo','Docker y WSL 2 no disponibles; PostgreSQL 18.6 existente','Usar instalación nativa y corregir locale sólo en base nueva vacía','Odoo 18 y módulos verificados; base preservada','Comprobar locale y filestore antes de crear datos'],['LA-02','Facturación','Facturas independientes inicialmente sin vínculo con órdenes','Crear facturas nativas tras recibir/entregar; cancelar sólo borradores independientes 25/26','Facturas 27/28 vinculadas y pagadas en laboratorio','No asumir trazabilidad por importe coincidente; exigir ID y origen'],['LA-03','Control de acceso','Grupos previstos no garantizan mínimo privilegio','Probar ACL y acceso por registro sin cambiar datos','H-01 documentado; cambio de roles pendiente','Revisar grupos implícitos y modelos secundarios antes de implantar']]),R(['Elaborado','Aprobado'],[[lead,'Pendiente: '+coordinator]])]},
  { n:20,title:'Informe de Cierre del Proyecto',sections:[R(['Rol','Nombre'],[['Patrocinador',sponsor],['Líder de Auditoría',lead],['Miembros de apoyo del equipo','Lucía Montes y Diego Ríos — gerentes del caso']]),R(['Evaluación de los objetivos del proyecto — Objetivo General','¿Cumple?','Observaciones'],[[objective,'PARCIAL','Pruebas técnicas y reconciliaciones realizadas; H-01 sin corrección autorizada ni aceptación. Cierre borrador.']]),R(['Objetivos Específicos','¿Cumple?','Observaciones'],[['Definir alcance y trazabilidad','Sí (documental)','Existe documentación, no aprobación institucional'],['Probar roles, registros y conciliación','Parcial','Flujos conciliados; H-01 de permisos sin remediar'],['Emitir informe basado en pruebas','Parcial','Anexo 17 con evidencia; revisión y firma pendientes']]),R(['Evaluación de los entregables — Entregable','¿Cumple?','Observaciones'],[['Entorno y datos','Sí (técnico)','Odoo nativo y datos de laboratorio verificados'],['Evidencia y trazabilidad','Sí (técnico)','Capturas Odoo y matrices con IDs; falta revisión de integridad por patrocinadora'],['Control y cierre','NO','Cambio de roles no autorizado ni implantado; cierre real no procede']]),R(['Elaborado','Aprobado'],[[lead,'No aprobado: proyecto abierto, requiere revisión humana y decisión sobre H-01']]) ]}
];

const escape = v => String(v ?? '').replaceAll(/\s*\(fictici[oa]s?\)/gi,'').replaceAll(/\s*\(coordinación ficticia\)/gi,'').replaceAll(/\bfictici[oa]s?\b/gi,'').replaceAll(/ {2,}/g,' ').replaceAll('|','\\|').replaceAll('\n','<br>');
// Enunciados documentales anteriores al despliegue: actualizar sólo el estado
// comprobable y conservar como pendientes las pruebas, aprobaciones y cierre.
const corrections = new Map([
  ['Odoo no instalado','Odoo 18 Community instalado; pruebas técnicas realizadas, aceptación pendiente'],
  ['Sin instancia no hay capacitación realizada','La instancia existe; capacitación no realizada'],
  ['Docker ausente','Ruta Docker ausente; se usó instalación nativa'],
  ['Alta (sin instancia)','Media (evidencia parcial)'],
  ['2 días; bloqueado','2 días previstos; entorno realizado anticipadamente'],
  ['Roles compartidos (hipótesis)','Permisos cruzados H-01 observados en laboratorio'],
  ['Roles mal asignados (hipótesis)','Accesos cruzados H-01 comprobados; cambio pendiente'],
  ['(hipótesis a verificar)','(hallazgo H-01 documentado; solicitud formal pendiente)'],
  ['Si las pruebas acreditan privilegios excesivos:','Según H-01 de permisos cruzados:'],
  ['Solicitud hipotética: no enviada, no autorizada, no probada ni implantada.','Propuesta respaldada por H-01: no enviada ni autorizada; el cambio de roles no fue probado ni implantado.'],
  ['Sin pruebas ni capturas','Sin disponibilidad de pruebas futuras'],
]);
const root = path.resolve('formularios');
for (const kind of ['vacios','diligenciados']) fs.mkdirSync(path.join(root,kind),{recursive:true});
for (const f of forms) {
  for (const kind of ['vacios','diligenciados']) {
    let text = `# Anexo ${f.n} — ${f.title}\n\n**${kindLabel(kind)}** · Fuente de estructura: Romero (2012), anexo ${f.n}.\n\n`;
    if (f.n !== 7 && f.n !== 16) text += `**PROYECTO:** ${kind === 'vacios' ? '________________' : P}\n\n`;
    for (const section of f.sections) {
      text += `| ${section.cols.map(escape).join(' | ')} |\n| ${section.cols.map(()=> '---').join(' | ')} |\n`;
      for (const row of section.rows) text += `| ${row.map(v => kind === 'vacios' ? '________' : escape(v)).join(' | ')} |\n`;
      text += '\n';
    }
    if(kind === 'diligenciados') {
      for (const [before,after] of corrections) text = text.replaceAll(before,after);
    }
    if(kind === 'vacios') text += '_Plantilla editable. Añada filas donde proceda._\n';
    fs.writeFileSync(path.join(root,kind,`anexo-${String(f.n).padStart(2,'0')}.md`),text);
  }
}
function kindLabel(k){return k === 'vacios'?'Plantilla vacía editable':'Versión diligenciada (estado documentado, no auditoría concluida)';}
console.log(`Generados ${forms.length} vacíos y ${forms.length} diligenciados.`);
